// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1fEMeEH2ylOo_5J1TCPQVouwRVdEVDg0',
    appId: '1:58065501341:web:70ce9b0ae2db236e632874',
    messagingSenderId: '58065501341',
    projectId: 'khikaya-17b41',
    authDomain: 'khikaya-17b41.firebaseapp.com',
    storageBucket: 'khikaya-17b41.appspot.com',
    measurementId: 'G-2QCT9G2TZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ0nHL9hnvqlPmuZlEh2o9mC5edCXxPvc',
    appId: '1:58065501341:android:a6a498e2d4462038632874',
    messagingSenderId: '58065501341',
    projectId: 'khikaya-17b41',
    storageBucket: 'khikaya-17b41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCddLTuVGXOQyaVXHGgrxkaKkmIllDE6DI',
    appId: '1:58065501341:ios:871e7c6c962c1b8d632874',
    messagingSenderId: '58065501341',
    projectId: 'khikaya-17b41',
    storageBucket: 'khikaya-17b41.appspot.com',
    iosClientId: '58065501341-hog5lchstmh8iqt1ft7k6jrj49t1j53d.apps.googleusercontent.com',
    iosBundleId: 'kz.khikaya.khikaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCddLTuVGXOQyaVXHGgrxkaKkmIllDE6DI',
    appId: '1:58065501341:ios:871e7c6c962c1b8d632874',
    messagingSenderId: '58065501341',
    projectId: 'khikaya-17b41',
    storageBucket: 'khikaya-17b41.appspot.com',
    iosClientId: '58065501341-hog5lchstmh8iqt1ft7k6jrj49t1j53d.apps.googleusercontent.com',
    iosBundleId: 'kz.khikaya.khikaya',
  );
}
